stages:
  data_ingestion:
    cmd: python -m src.data.data_ingestion
    deps:
    - src/data/data_ingestion.py
    - src/utils.py
    params:
    - data_ingestion.kaggle_competition
    - data_ingestion.exclude_files
    outs:
    - data/raw/train.csv
    - data/raw/test.csv
  
  data_preprocessing:
    cmd: python -m src.data.data_preprocessing
    deps:
    - src/data/data_preprocessing.py
    - src/utils.py
    - data/raw
    outs:
    - data/interim/titanic_cleaned.csv
  
  feature_engineering:
    cmd: python -m src.features.feature_engineering
    deps:
    - src/features/feature_engineering.py
    - src/utils.py
    - data/interim/titanic_cleaned.csv
    outs:
    - data/interim/feature_engineering.csv
