stages:
  data_ingestion:
    cmd: python -m src.data.data_ingestion
    deps:
    - src/data/data_ingestion.py
    - src/utils.py
    params:
    - data_ingestion.kaggle_competition
    - data_ingestion.exclude_files
    outs:
    - data/raw/train.csv
    - data/raw/test.csv
  
  data_preprocessing:
    cmd: python -m src.data.data_preprocessing
    deps:
    - src/data/data_preprocessing.py
    - src/utils.py
    - data/raw
    outs:
    - data/interim/titanic_cleaned.csv
  
  feature_engineering:
    cmd: python -m src.features.feature_engineering
    deps:
    - src/features/feature_engineering.py
    - src/utils.py
    - data/interim/titanic_cleaned.csv
    outs:
    - data/interim/feature_engineering.csv
  
  feature_encoding:
    cmd: python -m src.features.feature_encoding
    deps:
    - src/features/feature_encoding.py
    - src/utils.py
    - data/interim/feature_engineering.csv
    outs:
    - data/processed/features.csv
  
  split_data:
    cmd: python -m src.features.split_data
    deps:
    - src/features/split_data.py
    - data/processed/features.csv
    params:
    - split_data.test_size
    - split_data.random_state
    outs:
    - data/processed/train.csv
    - data/processed/validation.csv

  model_building:
    cmd: python -m src.models.model_building
    deps:
    - src/models/model_building.py
    - src/utils.py
    - data/processed/train.csv
    params:
    - model_building.max_depth
    - model_building.min_samples_split
    - model_building.n_estimators
    outs:
    - models/model.pkl

  model_evaluation:
    cmd: python -m src.models.model_evaluation
    deps:
      - src/models/model_evaluation.py
      - models/model.pkl
      - data/processed/validation.csv
    outs:
      - reports/metrics.json
      - reports/run_info.json
  
  model_registry:
    cmd: python -m src.models.register_model
    deps:
      - reports/metrics.json
      - reports/run_info.json
