stages:
  data_ingestion:
    cmd: python -m src.data.data_ingestion
    deps:
    - src/data/data_ingestion.py
    params:
    - data_ingestion.kaggle_competition
    - data_ingestion.exclude_files
    outs:
    - data/raw/train.csv
    - data/raw/test.csv
